---
name: Test building on Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Test with ${{ matrix.dependencies }} dependencies"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        dependencies: ['internal', 'external']

    steps:
      - name: Prepare build environment
        run: |
          sudo apt-get update -yy
          sudo apt-get install -yy --no-install-recommends \
            build-essential \
            libpurple-dev \
            meson

      - name: Install external dependencies
        if: matrix.dependencies == 'external'
        run: |
          sudo apt-get update -yy
          sudo apt-get install -yy --no-install-recommends \
            libgadu-dev \
            libmeanwhile-dev

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Setup Meson build
        run: meson setup build

      - name: Build project
        run: ninja -C build

      - name: Install build results
        run: DESTDIR=$PWD/dist ninja -C build install

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
        with:
          name: "Linux with ${{ matrix.dependencies }} dependencies"
          path: ./dist
